boards/urls.py
from django.urls import path, include
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.index, name='index'), #boards/
    path('new/', views.new, name='new'), #boards/new
    # path('create/', views.create, name='create'),
    path('<int:board_pk>/', views.detail, name='detail'),
    path('<int:board_pk>/edit/', views.edit, name='edit'),
    # path('<int:board_pk>/update/', views.update, name='update'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete')
]

django_recrud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
]

boards/models.py
from django.db import models

# Create your models here.
class boards(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'<boards({self.id}): {self.title}>'
        
class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    board = models.ForeignKey(boards, on_delete=models.CASCADE)
    # on_delete는 참조하는 객체가 삭제될 경우 설정
    # CASCADE : 같이 삭제
    # SET_NULL : NULL 값으로 변경(NOT NULL인 경우 불가능)
    # SET_DEFAULT : DEFAULT으로 변경(DEFAULT값 없으면 불가능)
    # PROTECT : 삭제 불가
    def __str__(self):
        return self.content

boards/views.py
from django.shortcuts import render, redirect
from .models import boards, Comment
# Create your views here.
def index(request):
    board = boards.objects.all()
    return render(request, 'boards/index.html', {'board':board})
    
def new(request):
    if request.method == 'POST':
        board = boards()
        board.title = request.POST.get('title')
        board.content = request.POST.get('content')
        board.save()
        return redirect('boards:detail', board.pk)
    else:
        return render(request, 'boards/new.html')
    
# def create(request):
#     board = boards()
#     board.title = request.POST.get('title')
#     board.content = request.POST.get('content')
#     board.save()
#     return redirect('boards:detail', board.pk)
    
def detail(request, board_pk):
    board = boards.objects.get(pk=board_pk)
    comments = board.comment_set.all()
    context = {
        'board':board,
        'comments':comments
    }
    return render(request, 'boards/detail.html', context)
    
def edit(request, board_pk):
    if request.method == 'POST':
        board = boards.objects.get(pk=board_pk)
        board.title = request.POST.get('title')
        board.content = request.POST.get('content')
        board.save()
        return redirect('boards:detail', board.pk)
    else:
        board = boards.objects.get(pk=board_pk)
        return render(request, 'boards/edit.html', {'board':board})
    
# def update(request, board_pk):
#     board = boards.objects.get(pk=board_pk)
#     board.title = request.POST.get('title')
#     board.content = request.POST.get('content')
#     board.save()
#     return redirect('boards:detail', board.pk)
    
def delete(request, board_pk):
    board = boards.objects.get(pk=board_pk)
    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')
    else:
        return redirect('boards:detail', board.pk)
        
def comment_create(request, board_pk):
    # 1. 댓글 달 게시물을 가져온다.
    board = boards.objects.get(pk=board_pk)
    # 2. 댓글을 저장한다.
    comment = Comment()
    comment.content = request.POST.get('content')
    comment.board = board
    comment.save()
    return redirect('boards:detail', board.pk)
    
def comments_delete(request, board_pk, comment_pk):
    if request.method == "POST":
        comment = Comment.objects.get(pk=comment_pk)
        comment.delete()
    return redirect('boards:detail', board_pk)

boards/templates/boards/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

boards/templates/boards/detail.html
{% extends 'boards/base.html' %}

{% block body %}
<p>id : {{board.pk }}</p>
<p>title : {{ board.title }}</p>
<p>content : {{ board.content }}</p>
<p>created_at : {{ board.created_at }}</p>
<p>updated_at : {{ board.updated_at }}</p>
<a href="{% url 'boards:index' %}">home</a>
<hr>
<p>댓글 작성</p>
<form action="{% url 'boards:comment_create' board.pk %}" method="POST">
    {% csrf_token %}
    <input type="text" name="content">
    <input type="submit">
</form>
{% for comment in comments %}
<li>{{ comment.content }} </li>
<form action="{% url 'boards:comments_delete' board.pk comment.pk %}" method="POST" style="display: inline" onsubmit="return confirm('삭제할거야?')">
    {% csrf_token %}
    <input type="submit" value="삭제">
</form>
{% endfor %}
{% endblock %}

boards/templates/boards/edit.html
{% extends 'boards/base.html' %}

{% block body %}
<form method='POST'>
    {% csrf_token %}
    <input type='text' name='title' value={{board.title}}>
    <input type='textarea' name='content' value={{board.content}}>
    <input type='submit'>
</form>
<a href="{% url 'boards:index' %}">home</a>
{% endblock %}

boards/templates/boards/index.html
{% extends 'boards/base.html' %}

{% block body %}
{% for bo in board %}
    <p>{{ bo.title }}</p>
    <p>{{ bo.content }}</p>
    <a href="{% url 'boards:detail' bo.pk %}">상세보기</a>
    <a href="{% url 'boards:edit' bo.pk %}">수정하기</a>
    <form action="{% url 'boards:delete' bo.pk %}" method="POST" style='display: inline' onsubmit="return confirm('삭제할거야?')">
        {% csrf_token %}
        <input type='submit' value='삭제하기'>
    </form>
    <hr>
{% endfor %}
<a href="{% url 'boards:new' %}">새로만들기</a>
{% endblock %}

boards/templates/boards/new.html
{% extends 'boards/base.html' %}

{% block body %}
<form action="{% url 'boards:new' %}" method='POST'>
    {% csrf_token %}
    title : <input type='text' name='title'>
    content :<input type='textarea' name='content'>
    <input type='submit'>
</form>

{% endblock %}